Update JNA library to version 5.13.0
There werde errors installing the file refresh monitor:

java.lang.NoClassDefFoundError: Could not initialize class org.objectstyle.wolips.goodies.core.mac.jna.CoreServices$CoreServicesWrapper
	at org.objectstyle.wolips.goodies.core.mac.MacRefreshProvider.installMonitor(MacRefreshProvider.java:15)
	at org.eclipse.core.resources.refresh.RefreshProvider.installMonitor(RefreshProvider.java:92)
[...]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Unable to load library 'CoreServices': dlopen(libCoreServices.dylib, 0x0009): tried: 'libCoreServices.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibCoreServices.dylib' (no such file), '/usr/lib/libCoreServices.dylib' (no such file, not in dyld cache), 'libCoreServices.dylib' (no such file), '/usr/lib/libCoreServices.dylib' (no such file, not in dyld cache) [in thread "main"]
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:155)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:216)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:191)
	at com.sun.jna.Library$Handler.<init>(Library.java:131)
	at com.sun.jna.Native.loadLibrary(Native.java:279)
	at com.sun.jna.Native.loadLibrary(Native.java:265)
	at org.objectstyle.wolips.goodies.core.mac.jna.CoreServices.<clinit>(CoreServices.java:14)
	at org.objectstyle.wolips.goodies.core.mac.jna.CoreServices$CoreServicesWrapper.<clinit>(CoreServices.java:66)
	... 50 more

A culprit seems the way macos bigsur and later handle core libraries. The library file is no longer present in the file system, but resides only in a liner cache. Tools should not search the file system for specific libaries, but must simply try to open the library. By updating the JNA library the errors went away.